### ISSUE TITLE
Cannot truncate a table referenced in a foreign key constraint 

### ISSUE THREAD

**Issue by migmake** [carlcs/craft-deleteallentryversions#2] opened 2016-07-26 13:15 UTC
CDbCommand n'a pas pu exécuter la commande SQL : SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint (`unep28`.`craft_import_entries`, CONSTRAINT `craft_import_entries_versionId_fk` FOREIGN KEY (`versionId`) REFERENCES `unep28`.`craft_entryversions` (`id`)). The SQL statement executed was: TRUNCATE TABLE `craft_entryversions`
![screen shot 2016-07-26 at 15 13 54](https://cloud.githubusercontent.com/assets/3531623/17139189/af74d3b6-5343-11e6-8b5f-5910578d6683.jpg)

**Comment by cole007** [comment] 2016-10-20 11:51
Likewise. Same problem

**Comment by cole007** [comment] 2016-10-20 13:19
Only way could resolve this was by using `DELETE FROM craft_entryversions` rather than `TRUNCATE craft_entryversions` - like @migswd this also seems to be a result of using the Import plugin at https://github.com/boboldehampsink/import

There does appear to be a `DELETE` cascade in the definition of the Records for the `import` plugin but not `UPDATE` so not sure if that is the cause of the problem

**Comment by carlcs** [comment] 2017-06-26 14:20
The plugin doesn’t truncate the `entryversions` table any longer, so this should be fixed.

**Closed as completed by carlcs** 2017-06-26 14:20 UTC
